version: '3.8'

services:
  site_alliance_elendil:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "38011:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      VIRTUAL_HOST: jean-marcillac.dev
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: jean-marcillac.dev
      LETSENCRYPT_EMAIL: jean.marcillac12@gmail.com
    container_name: portfolio-siwa
    restart: unless-stopped
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
